CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  fullname VARCHAR(100) NOT NULL,
  profile_description VARCHAR(280) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS tweets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text VARCHAR(280) NOT NULL CHECK (char_length(trim(text)) > 0),
  author VARCHAR(50) NOT NULL REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO users (id, username, fullname, profile_description)
VALUES
  (1, 'alice', 'Alice', ''),
  (2, 'bob', 'Bob', ''),
  (3, 'charlie', 'Charlie', '')
ON CONFLICT (username) DO NOTHING;

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE(MAX(id), 1), true)
FROM users;

INSERT INTO tweets (id, text, author)
VALUES
  (1, 'Hello Twitter!', 'alice'),
  (2, 'Mein zweiter Tweet', 'bob')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('tweets', 'id'), COALESCE(MAX(id), 1), true)
FROM tweets;

